name: goreleaser
on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: v1.14.1
          args: check
